[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pyeval"
version = "0.3.0"
description = "Conveniently evaluate Python expressions from the shell"
authors = [{name = "Nathan Wilcox", email = "nejucomo@gmail.com"}]
license = {text = "GPLv3"}
requires-python = ">=3.8"

[project.scripts]
pyeval = "pyeval.main:main"

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
pyeval = ["doc/*.txt"]

[tool.pytest.ini_options]
addopts = "--tb=short"
testpaths = ["src/pyeval/tests"]

[tool.coverage.run]
branch = true
source = ["pyeval"]

[tool.coverage.report]
show_missing = true
